### ISSUE TITLE
Printed equivalent widths are unrealistically small.

### ISSUE THREAD

**Issue by mwanakijiji** [czwa/robospect.py#30] opened 2019-11-12 20:03 UTC
It appears that the equivalent widths returned in the Robospect *.robolines output files are unrealistic. 

Specifically, the *.robolines files print EWs which are too small (very roughly by a factor of 10), but it is not a simple scaling error. The latter seems to be the case given  1.) Rough by-eye measurements of the EWs of the fit lines in Robospect's *.pdf plots, which vary from their *.robolines values in a non-linear way, and 2.) the plotted EWs from stellar spectra as a function of each other (specifically, of CaIIK lines as a function of Balmer lines) behave unphysically (they should be roughly straight lines for most temperatures, and converge for different metallicities at high temperatures, but the lines loop around in strange ways and do not converge).

However, the Robospect fits to normalized spectra (using Gaussian absorption line models) look fine, even with different levels of spectral S/N. So there appears to be a bug (which kicks in for large lines, at least) between the fitted line and the printed values in the *.robolines files.

Attached are 

1.  To demonstrate the good line fit: sn_10_example_model_fit.pdf, which shows an example plot of data from a *.robospect file, with input (blue) and the fit (orange). 
[sn_10_example_model_fit.pdf](https://github.com/czwa/robospect.py/files/3837893/sn_10_example_model_fit.pdf)

2.  To demonstrate the inconsistency between the *.robolines and *.pdf outputs: Two example *.pdf and corresponding *.robolines files, where the EW values should be ~1-10 AA (which the *pdf plots seem to show, as measured by-eye), but are printed in the *.robolines files as ~0.2-0.6 AA.

[775030m15.smo_000.pdf](https://github.com/czwa/robospect.py/files/3837881/775030m15.smo_000.pdf)
[700030m25.smo_000.pdf](https://github.com/czwa/robospect.py/files/3837884/700030m25.smo_000.pdf)
[775030m15.smo_000.txt](https://github.com/czwa/robospect.py/files/3837889/775030m15.smo_000.txt)
[700030m25.smo_000.txt](https://github.com/czwa/robospect.py/files/3837890/700030m25.smo_000.txt)

3.  To reproduce the error: 
ll.txt: a line list
725020m15.txt: an input spectrum
[ll.txt](https://github.com/czwa/robospect.py/files/3837964/ll.txt)
[725020m15.txt](https://github.com/czwa/robospect.py/files/3837979/725020m15.txt)
... to be processed with the command 
python /[..]rSpect.py -i 4 /[...]700030m30.smo_000 -P /[...]/[output name] --line_list ll -C name null -D name null -N name boxcar -I range 10.0 -F chi_window 20.0 -vvvv

**Comment by mwanakijiji** [comment] 2019-11-12 20:21
Here are histograms showing the disagreement between Robospect and IRAF, on a tranche of synthetic spectra. Histograms show measured EWs for Hbeta, Hgamma, Hdelta, and CaIIK.

[iraf_hdelta_ews.pdf](https://github.com/czwa/robospect.py/files/3838053/iraf_hdelta_ews.pdf)
[iraf_hgamma_ews.pdf](https://github.com/czwa/robospect.py/files/3838054/iraf_hgamma_ews.pdf)
[iraf_hbeta_ews.pdf](https://github.com/czwa/robospect.py/files/3838055/iraf_hbeta_ews.pdf)
[iraf_caiik_ews.pdf](https://github.com/czwa/robospect.py/files/3838056/iraf_caiik_ews.pdf)

[robospect_hdelta_eqw_hist.pdf](https://github.com/czwa/robospect.py/files/3838059/robospect_hdelta_eqw_hist.pdf)
[robospect_hbeta_eqw_hist.pdf](https://github.com/czwa/robospect.py/files/3838060/robospect_hbeta_eqw_hist.pdf)
[robospect_caiik_eqw_hist.pdf](https://github.com/czwa/robospect.py/files/3838061/robospect_caiik_eqw_hist.pdf)
[robospect_hgamma_eqw_hist.pdf](https://github.com/czwa/robospect.py/files/3838062/robospect_hgamma_eqw_hist.pdf)

**Comment by czwa** [comment] 2019-11-19 21:41
This should be resolved by the tickets/feat-30 branch, which updates the equivalent width calculation to respect a change in the model flux definition I'd forgotten about.

**Comment by czwa** [comment] 2019-12-29 23:52
Merging feature branch and marking this issue closed.  Please reopen if the issue is still happening.

**Closed by czwa** 2019-12-29 23:52 UTC
